// SPDX-License-Identifier: MIT
// Comprehensive tests for the Java codegen backend
//
// Verifies that the Java backend produces correct output for all protocol
// features, matching the coverage of the C++ codegen test suite.

#include <catch2/catch_test_macros.hpp>
#include "../src/model/ast_builder.hpp"
#include "../src/analyzer/type_resolver.hpp"
#include "../src/analyzer/validator.hpp"
#include "../src/analyzer/wire_sizer.hpp"
#include "../src/analyzer/session_analyzer.hpp"
#include "../src/codegen/java_backend.hpp"
#include <filesystem>
#include <fstream>
#include <map>
#include <string>

namespace fs = std::filesystem;

static std::string fixture_path(const std::string& name) {
    return (fs::path(BGEN_TEST_FIXTURES_DIR) / name).string();
}

struct GeneratedJava {
    std::map<std::string, std::string> files;
};

static std::string read_file(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    return {std::istreambuf_iterator<char>(in), {}};
}

static std::optional<GeneratedJava> gen_java(const std::string& fixture) {
    auto build = bgen::model::build_protocol(fixture_path(fixture));
    if (!build) return std::nullopt;
    auto& protocol = *build;

    auto resolve = bgen::analyzer::resolve_types(protocol);
    if (!resolve) return std::nullopt;
    auto& index = *resolve;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);

    std::string ns = protocol.name;
    for (char& c : ns) if (c == '-') c = '_';

    auto tmp = fs::temp_directory_path() / ("bgen_test_java_" + ns);
    fs::create_directories(tmp);

    bgen::codegen::JavaBackend backend;
    if (!backend.generate(protocol, index, sizes, sessions, ns, tmp))
        return std::nullopt;

    GeneratedJava gj;
    for (auto& entry : fs::recursive_directory_iterator(tmp))
        if (entry.is_regular_file())
            gj.files[entry.path().filename().string()] = read_file(entry.path());

    fs::remove_all(tmp);
    return gj;
}

// ============================================================================
// File generation tests
// ============================================================================

TEST_CASE("Java: generates infrastructure files", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.count("BitReader.java"));
    CHECK(java->files.count("BitWriter.java"));
    CHECK(java->files.count("ConduitCodecException.java"));
    CHECK(java->files.count("Constants.java"));
    CHECK(java->files.count("Protocol.java"));
}

TEST_CASE("Java: all generated files have package declaration", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    for (const auto& [name, content] : java->files) {
        INFO("File: " << name);
        CHECK(content.find("package ") != std::string::npos);
    }
}

TEST_CASE("Java: all generated files start with generated header", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    for (const auto& [name, content] : java->files) {
        INFO("File: " << name);
        CHECK(content.find("Generated by bgen") != std::string::npos);
    }
}

// ============================================================================
// BitReader tests
// ============================================================================

TEST_CASE("Java: BitReader has all read methods", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& br = java->files["BitReader.java"];
    CHECK(br.find("readBits(") != std::string::npos);
    CHECK(br.find("readSignedBits(") != std::string::npos);
    CHECK(br.find("readU8()") != std::string::npos);
    CHECK(br.find("readU16(") != std::string::npos);
    CHECK(br.find("readU32(") != std::string::npos);
    CHECK(br.find("readU64(") != std::string::npos);
    CHECK(br.find("readF32(") != std::string::npos);
    CHECK(br.find("readF64(") != std::string::npos);
    CHECK(br.find("readString(") != std::string::npos);
    CHECK(br.find("readBytes(") != std::string::npos);
    CHECK(br.find("readBcd(") != std::string::npos);
    CHECK(br.find("readBcdSigned(") != std::string::npos);
    CHECK(br.find("readSignMagnitude(") != std::string::npos);
}

TEST_CASE("Java: BitReader has utility methods", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& br = java->files["BitReader.java"];
    CHECK(br.find("remainingBytes()") != std::string::npos);
    CHECK(br.find("skipBits(") != std::string::npos);
    CHECK(br.find("subReader(") != std::string::npos);
}

TEST_CASE("Java: BitReader uses ByteBuffer for endianness", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& br = java->files["BitReader.java"];
    CHECK(br.find("ByteBuffer") != std::string::npos);
    CHECK(br.find("ByteOrder.BIG_ENDIAN") != std::string::npos);
    CHECK(br.find("ByteOrder.LITTLE_ENDIAN") != std::string::npos);
}

// ============================================================================
// BitWriter tests
// ============================================================================

TEST_CASE("Java: BitWriter has all write methods", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& bw = java->files["BitWriter.java"];
    CHECK(bw.find("writeBits(") != std::string::npos);
    CHECK(bw.find("writeSignedBits(") != std::string::npos);
    CHECK(bw.find("writeU8(") != std::string::npos);
    CHECK(bw.find("writeU16(") != std::string::npos);
    CHECK(bw.find("writeU32(") != std::string::npos);
    CHECK(bw.find("writeU64(") != std::string::npos);
    CHECK(bw.find("writeF32(") != std::string::npos);
    CHECK(bw.find("writeF64(") != std::string::npos);
    CHECK(bw.find("writeString(") != std::string::npos);
    CHECK(bw.find("writeBytes(") != std::string::npos);
    CHECK(bw.find("writeBcd(") != std::string::npos);
    CHECK(bw.find("writeBcdSigned(") != std::string::npos);
    CHECK(bw.find("writeSignMagnitude(") != std::string::npos);
}

TEST_CASE("Java: BitWriter has patch methods", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& bw = java->files["BitWriter.java"];
    CHECK(bw.find("patchU8(") != std::string::npos);
    CHECK(bw.find("patchU16(") != std::string::npos);
    CHECK(bw.find("patchU32(") != std::string::npos);
}

TEST_CASE("Java: BitWriter has sizeBytes and toBytes", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& bw = java->files["BitWriter.java"];
    CHECK(bw.find("sizeBytes()") != std::string::npos);
    CHECK(bw.find("toBytes()") != std::string::npos);
}

// ============================================================================
// Exception class tests
// ============================================================================

TEST_CASE("Java: ConduitCodecException extends RuntimeException", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& exc = java->files["ConduitCodecException.java"];
    CHECK(exc.find("extends RuntimeException") != std::string::npos);
}

// ============================================================================
// Message class tests
// ============================================================================

TEST_CASE("Java: message class has decode/encode methods", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["SimpleMessage.java"];
    CHECK(msg.find("public final class SimpleMessage") != std::string::npos);
    CHECK(msg.find("public static SimpleMessage decode(BitReader r)") != std::string::npos);
    CHECK(msg.find("public void encode(BitWriter w)") != std::string::npos);
    CHECK(msg.find("decodeBytes") != std::string::npos);
    CHECK(msg.find("encodeBytes") != std::string::npos);
}

TEST_CASE("Java: message class has TYPE_ID and TYPE_NAME", "[java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AlphaBody.java"];
    CHECK(msg.find("TYPE_ID") != std::string::npos);
    CHECK(msg.find("TYPE_NAME") != std::string::npos);
}

TEST_CASE("Java: message class has toString", "[java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["SimpleMessage.java"];
    CHECK(msg.find("@Override public String toString()") != std::string::npos);
}

// ============================================================================
// Basic type tests
// ============================================================================

TEST_CASE("Java: bool field uses ternary encode (not int cast)", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("this.flag ? 1 : 0") != std::string::npos);
    CHECK(msg.find("(int)this.flag") == std::string::npos);
}

TEST_CASE("Java: bool field decode uses != 0 comparison", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("!= 0)") != std::string::npos);
}

TEST_CASE("Java: float uses 0.0f init, double uses 0.0 init", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("public float f32 = 0.0f;") != std::string::npos);
    CHECK(msg.find("public double f64 = 0.0;") != std::string::npos);
    CHECK(msg.find("double f64 = 0.0f") == std::string::npos);
}

TEST_CASE("Java: LE fields use false for big-endian parameter", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("readU16(false)") != std::string::npos);
    CHECK(msg.find("readU32(false)") != std::string::npos);
}

TEST_CASE("Java: BE fields use true for big-endian parameter", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("readU16(true)") != std::string::npos);
}

// ============================================================================
// Enum type tests
// ============================================================================

TEST_CASE("Java: enum type generates Java enum class", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("ColorEnum.java"));
    auto& ce = java->files["ColorEnum.java"];
    CHECK(ce.find("public enum ColorEnum") != std::string::npos);
    CHECK(ce.find("RED(") != std::string::npos);
    CHECK(ce.find("GREEN(") != std::string::npos);
    CHECK(ce.find("BLUE(") != std::string::npos);
    CHECK(ce.find("public final int value;") != std::string::npos);
    CHECK(ce.find("decode(BitReader r)") != std::string::npos);
    CHECK(ce.find("encode(BitWriter w)") != std::string::npos);
}

TEST_CASE("Java: enum decode throws on unknown value", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& ce = java->files["ColorEnum.java"];
    CHECK(ce.find("throw new ConduitCodecException") != std::string::npos);
}

// ============================================================================
// Flags type tests
// ============================================================================

TEST_CASE("Java: flags type uses long raw and 1L shift", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("StatusFlags.java"));
    auto& sf = java->files["StatusFlags.java"];
    CHECK(sf.find("private long raw;") != std::string::npos);
    CHECK(sf.find("1L<<") != std::string::npos);
}

TEST_CASE("Java: flags type has getter and setter for each flag", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& sf = java->files["StatusFlags.java"];
    CHECK(sf.find("public boolean") != std::string::npos);
    CHECK(sf.find("public void set") != std::string::npos);
}

// ============================================================================
// Scaled type tests
// ============================================================================

TEST_CASE("Java: scaled type generates wrapper class with value()", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("ScaledTemp.java"));
    auto& st = java->files["ScaledTemp.java"];
    CHECK(st.find("public final class ScaledTemp") != std::string::npos);
    CHECK(st.find("0.01") != std::string::npos);
    CHECK(st.find("double value()") != std::string::npos);
    CHECK(st.find("decode(BitReader r)") != std::string::npos);
    CHECK(st.find("encode(BitWriter w)") != std::string::npos);
}

// ============================================================================
// Constants tests
// ============================================================================

TEST_CASE("Java: Constants class has protocol constants", "[java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& consts = java->files["Constants.java"];
    CHECK(consts.find("public final class Constants") != std::string::npos);
    CHECK(consts.find("SYNC") != std::string::npos);
    CHECK(consts.find("public static final long") != std::string::npos);
}

// ============================================================================
// Struct tests
// ============================================================================

TEST_CASE("Java: struct types get separate .java files", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.count("TypeABody.java"));
    CHECK(java->files.count("TypeBBody.java"));
    CHECK(java->files.count("Point.java"));
}

TEST_CASE("Java: struct class has public fields with defaults", "[java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("public ") != std::string::npos);
    CHECK(msg.find("= 0;") != std::string::npos);
}

// ============================================================================
// Array tests
// ============================================================================

TEST_CASE("Java: arrays have List type with ArrayList init", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["FixedArrayMsg.java"];
    CHECK(msg.find("java.util.List<") != std::string::npos);
    CHECK(msg.find("new java.util.ArrayList<>()") != std::string::npos);
}

TEST_CASE("Java: fixed-count array uses for loop", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["FixedArrayMsg.java"];
    CHECK(msg.find("for (int _i=0;") != std::string::npos);
}

TEST_CASE("Java: array encode iterates with for-each", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["FixedArrayMsg.java"];
    CHECK(msg.find("for (var _item") != std::string::npos);
}

// ============================================================================
// Choice tests
// ============================================================================

TEST_CASE("Java: inline choice types get separate files", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.count("TypeABody.java"));
    CHECK(java->files.count("TypeBBody.java"));
    CHECK(java->files.count("FallbackBody.java"));
}

TEST_CASE("Java: choice decode uses if/else if dispatch", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("if (") != std::string::npos);
    CHECK(all.find("} else if (") != std::string::npos);
}

TEST_CASE("Java: choice encode uses instanceof check", "[java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("instanceof") != std::string::npos);
}

// ============================================================================
// String feature tests
// ============================================================================

TEST_CASE("Java: fixed-length string decode with readString", "[java]") {
    auto java = gen_java("string_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("readString(") != std::string::npos);
}

TEST_CASE("Java: string field initialized to empty string", "[java]") {
    auto java = gen_java("string_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("= \"\";") != std::string::npos);
}

TEST_CASE("Java: string encode uses writeString", "[java]") {
    auto java = gen_java("string_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("writeString(") != std::string::npos);
}

TEST_CASE("Java: fixed-length string decode trims padding", "[java]") {
    auto java = gen_java("string_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("endsWith(") != std::string::npos);
    CHECK(all.find("substring(") != std::string::npos);
}

// ============================================================================
// Wire encoding tests (BCD, BCD_S, BNR_S)
// ============================================================================

TEST_CASE("Java: BCD field uses readBcd/writeBcd", "[java]") {
    auto java = gen_java("wire_encodings.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("readBcd(") != std::string::npos);
    CHECK(all.find("writeBcd(") != std::string::npos);
}

TEST_CASE("Java: BCD_S field uses readBcdSigned/writeBcdSigned", "[java]") {
    auto java = gen_java("wire_encodings.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("readBcdSigned(") != std::string::npos);
    CHECK(all.find("writeBcdSigned(") != std::string::npos);
}

TEST_CASE("Java: BNR_S field uses readSignMagnitude/writeSignMagnitude", "[java]") {
    auto java = gen_java("wire_encodings.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("readSignMagnitude(") != std::string::npos);
    CHECK(all.find("writeSignMagnitude(") != std::string::npos);
}

// ============================================================================
// Mixed endian tests
// ============================================================================

TEST_CASE("Java: mixed endian protocol uses both true and false", "[java]") {
    auto java = gen_java("mixed_endian.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("true") != std::string::npos);
    CHECK(all.find("false") != std::string::npos);
}

// ============================================================================
// Field scale/offset tests
// ============================================================================

TEST_CASE("Java: field-level scale generates multiply/add decode", "[java]") {
    auto java = gen_java("field_scale.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("* ") != std::string::npos);
}

TEST_CASE("Java: field-level scale generates inverse encode", "[java]") {
    auto java = gen_java("field_scale.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("/ ") != std::string::npos);
}

// ============================================================================
// Protocol tests
// ============================================================================

TEST_CASE("Java: Protocol class has type registry", "[java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& prot = java->files["Protocol.java"];
    CHECK(prot.find("public final class Protocol") != std::string::npos);
    CHECK(prot.find("TypeInfo") != std::string::npos);
    CHECK(prot.find("findById") != std::string::npos);
    CHECK(prot.find("findByName") != std::string::npos);
}

TEST_CASE("Java: Protocol class has NAME and VERSION", "[java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& prot = java->files["Protocol.java"];
    CHECK(prot.find("public static final String NAME") != std::string::npos);
    CHECK(prot.find("public static final String VERSION") != std::string::npos);
}

TEST_CASE("Java: Protocol type registry lists leaf types", "[java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& prot = java->files["Protocol.java"];
    CHECK(prot.find("AlphaBody") != std::string::npos);
    CHECK(prot.find("BetaBody") != std::string::npos);
}

// ============================================================================
// Inline field type tests
// ============================================================================

TEST_CASE("Java: inline field types generate correct output", "[java]") {
    auto java = gen_java("inline_field_types.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Bytes field tests
// ============================================================================

TEST_CASE("Java: byte[] field toString uses Arrays.toString", "[java]") {
    auto java = gen_java("bytes_numeric.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("LargeBytesMsg.java"));
    auto& msg = java->files["LargeBytesMsg.java"];
    CHECK(msg.find("java.util.Arrays.toString(blob)") != std::string::npos);
}

TEST_CASE("Java: bytes field initialized to empty array", "[java]") {
    auto java = gen_java("bytes_numeric.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("new byte[0]") != std::string::npos);
}

TEST_CASE("Java: bytes field uses readBytes/writeBytes", "[java]") {
    auto java = gen_java("bytes_numeric.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("readBytes(") != std::string::npos);
    CHECK(all.find("writeBytes(") != std::string::npos);
}

// ============================================================================
// present_when tests
// ============================================================================

TEST_CASE("Java: present_when on struct generates conditional decode", "[java]") {
    auto java = gen_java("present_when_complex.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("if (") != std::string::npos);
}

TEST_CASE("Java: present_when on array generates conditional decode", "[java]") {
    auto java = gen_java("present_when_complex.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    // Expression renders as decimal: flags & 1
    CHECK(all.find("flags") != std::string::npos);
    CHECK(all.find("& 1)") != std::string::npos);
}

TEST_CASE("Java: present_when on choice generates conditional decode", "[java]") {
    auto java = gen_java("present_when_complex.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    // Expression renders as decimal: flags & 2
    CHECK(all.find("& 2)") != std::string::npos);
}

// ============================================================================
// Reserved field tests
// ============================================================================

TEST_CASE("Java: reserved field generates skipBits", "[java]") {
    auto java = gen_java("struct_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("skipBits(") != std::string::npos);
}

TEST_CASE("Java: reserved field encode writes zeros", "[java]") {
    auto java = gen_java("struct_features.bmdl.xml");
    REQUIRE(java.has_value());
    std::string all;
    for (const auto& [name, content] : java->files) all += content;
    CHECK(all.find("writeBits(0, ") != std::string::npos);
}

// ============================================================================
// Expression tests
// ============================================================================

TEST_CASE("Java: expression features generate output", "[java]") {
    auto java = gen_java("expr_features.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Frame tests
// ============================================================================

TEST_CASE("Java: basic frame generates output", "[java]") {
    auto java = gen_java("frame_basic.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame with config generates output", "[java]") {
    auto java = gen_java("frame_config.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame with footer generates output", "[java]") {
    auto java = gen_java("frame_footer.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame with direction generates output", "[java]") {
    auto java = gen_java("frame_direction.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame with array generates output", "[java]") {
    auto java = gen_java("frame_array.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame with timestamp generates output", "[java]") {
    auto java = gen_java("frame_timestamp.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame length offset generates output", "[java]") {
    auto java = gen_java("frame_length_offset.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame count generates output", "[java]") {
    auto java = gen_java("frame_count.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame payload length generates output", "[java]") {
    auto java = gen_java("frame_payload_length.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame payload length from generates output", "[java]") {
    auto java = gen_java("frame_payload_length_from.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: frame length arith generates output", "[java]") {
    auto java = gen_java("frame_length_arith.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Inline enum tests
// ============================================================================

TEST_CASE("Java: inline enum generates output", "[java]") {
    auto java = gen_java("inline_enum.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Auto-field tests
// ============================================================================

TEST_CASE("Java: auto-sequence generates output", "[java]") {
    auto java = gen_java("auto_sequence.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: auto-count generates output", "[java]") {
    auto java = gen_java("auto_count.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: auto-struct-length generates output", "[java]") {
    auto java = gen_java("auto_struct_length.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Format binary tests
// ============================================================================

TEST_CASE("Java: format binary generates output", "[java]") {
    auto java = gen_java("format_binary.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// FX block tests
// ============================================================================

TEST_CASE("Java: FX block generates correct output", "[java]") {
    auto java = gen_java("fx_block.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: FX advanced generates output", "[java]") {
    auto java = gen_java("fx_advanced.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: FX choice generates output", "[java]") {
    auto java = gen_java("fx_choice.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: FX string generates output", "[java]") {
    auto java = gen_java("fx_string.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Bitmap tests
// ============================================================================

TEST_CASE("Java: bitmap FX protocol generates output", "[java]") {
    auto java = gen_java("bitmap_fx.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: bitmap advanced generates output", "[java]") {
    auto java = gen_java("bitmap_advanced.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: bitmap wide fixed generates output", "[java]") {
    auto java = gen_java("bitmap_wide_fixed.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Edge case fixture tests
// ============================================================================

TEST_CASE("Java: EBCDIC strings generate output", "[java]") {
    auto java = gen_java("ebcdic_strings.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: inline case collision generates output", "[java]") {
    auto java = gen_java("inline_case_collision.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: optional constrained generates output", "[java]") {
    auto java = gen_java("optional_constrained.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: boundary types generate output", "[java]") {
    auto java = gen_java("boundary_types.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: default initial values generate output", "[java]") {
    auto java = gen_java("default_initial.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: string prefix incl generates output", "[java]") {
    auto java = gen_java("string_prefix_incl.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: enum arrays generate output", "[java]") {
    auto java = gen_java("enum_arrays.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: signed length fields generate output", "[java]") {
    auto java = gen_java("signed_length.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: send-only leaf generates output", "[java]") {
    auto java = gen_java("send_only_leaf.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: stress large protocol generates output", "[java]") {
    auto java = gen_java("stress_large.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: constraint tighten generates output", "[java]") {
    auto java = gen_java("constraint_tighten.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: direction qualified generates output", "[java]") {
    auto java = gen_java("direction_qualified.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: outer scope generates output", "[java]") {
    auto java = gen_java("outer_scope.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: FX IA5 string generates output", "[java]") {
    auto java = gen_java("fx_ia5_string.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: msg config generates output", "[java]") {
    auto java = gen_java("msg_config.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: msg config inline generates output", "[java]") {
    auto java = gen_java("msg_config_inline.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: constants everywhere generates output", "[java]") {
    auto java = gen_java("constants_everywhere.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: type name override generates output", "[java]") {
    auto java = gen_java("type_name_override.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: constraints generates output", "[java]") {
    auto java = gen_java("constraints.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: constraints extended generates output", "[java]") {
    auto java = gen_java("constraints_extended.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: length arith generates output", "[java]") {
    auto java = gen_java("length_arith.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: non-overlap ranges generates output", "[java]") {
    auto java = gen_java("non_overlap_ranges.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: nested choice passes outer-scope params to inner decode", "[java][nested]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    // Typed inline case is parent-prefixed to prevent collisions across messages
    CHECK(java->files.count("NestedChoiceMsgTyped.java"));
    auto& typed = java->files["NestedChoiceMsgTyped.java"];
    CHECK(typed.find("decode(BitReader r, int subType)") != std::string::npos);
}

TEST_CASE("Java: deep nested choice generates 3-level classes with outer params", "[java][nested]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    // 3-level deep: classes are parent-prefixed to prevent collisions
    CHECK(java->files.count("DeepNestedMsgL1.java"));
    CHECK(java->files.count("DeepNestedMsgL1L2.java"));
    CHECK(java->files.count("DeepNestedMsgL1L2L3.java"));
    auto& l1 = java->files["DeepNestedMsgL1.java"];
    auto& l2 = java->files["DeepNestedMsgL1L2.java"];
    CHECK(l1.find("decode(BitReader r, int typeB, int typeC)") != std::string::npos);
    CHECK(l2.find("decode(BitReader r, int typeC)") != std::string::npos);
}

TEST_CASE("Java: session protocol generates output", "[java]") {
    auto java = gen_java("session_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

TEST_CASE("Java: struct features generate output", "[java]") {
    auto java = gen_java("struct_features.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(!java->files.empty());
}

// ============================================================================
// Java backend basic codegen tests (moved from cross-backend tests)
// ============================================================================

TEST_CASE("Java: generates infrastructure files", "[codegen][java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.count("BitReader.java"));
    CHECK(java->files.count("BitWriter.java"));
    CHECK(java->files.count("ConduitCodecException.java"));
    CHECK(java->files.count("Constants.java"));
    CHECK(java->files.count("Protocol.java"));
}

TEST_CASE("Java: message class has decode/encode", "[codegen][java]") {
    auto java = gen_java("minimal.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["SimpleMessage.java"];
    CHECK(msg.find("public final class SimpleMessage") != std::string::npos);
    CHECK(msg.find("public static SimpleMessage decode(BitReader r)") != std::string::npos);
    CHECK(msg.find("public void encode(BitWriter w)") != std::string::npos);
    CHECK(msg.find("decodeBytes") != std::string::npos);
    CHECK(msg.find("encodeBytes") != std::string::npos);
}

TEST_CASE("Java: bool field uses correct encode (not (int)cast)", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("this.flag ? 1 : 0") != std::string::npos);
    CHECK(msg.find("(int)this.flag") == std::string::npos);
}

TEST_CASE("Java: double field uses 0.0 init (not 0.0f)", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("public float f32 = 0.0f;") != std::string::npos);
    CHECK(msg.find("public double f64 = 0.0;") != std::string::npos);
    CHECK(msg.find("double f64 = 0.0f") == std::string::npos);
}

TEST_CASE("Java: enum type generates enum class", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("ColorEnum.java"));
    auto& ce = java->files["ColorEnum.java"];
    CHECK(ce.find("public enum ColorEnum") != std::string::npos);
    CHECK(ce.find("RED(") != std::string::npos);
    CHECK(ce.find("GREEN(") != std::string::npos);
    CHECK(ce.find("BLUE(") != std::string::npos);
    CHECK(ce.find("decode(BitReader r)") != std::string::npos);
    CHECK(ce.find("encode(BitWriter w)") != std::string::npos);
}

TEST_CASE("Java: flags type uses long raw", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("StatusFlags.java"));
    auto& sf = java->files["StatusFlags.java"];
    CHECK(sf.find("private long raw;") != std::string::npos);
    CHECK(sf.find("1L<<") != std::string::npos);
}

TEST_CASE("Java: scaled type generates wrapper class", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("ScaledTemp.java"));
    auto& st = java->files["ScaledTemp.java"];
    CHECK(st.find("public final class ScaledTemp") != std::string::npos);
    CHECK(st.find("0.01") != std::string::npos);
    CHECK(st.find("double value()") != std::string::npos);
}

TEST_CASE("Java: inline choice types get separate files", "[codegen][java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.count("TypeABody.java"));
    CHECK(java->files.count("TypeBBody.java"));
    CHECK(java->files.count("FallbackBody.java"));
}

TEST_CASE("Java: arrays have List type", "[codegen][java]") {
    auto java = gen_java("arrays_choices.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["FixedArrayMsg.java"];
    CHECK(msg.find("java.util.List<") != std::string::npos);
    CHECK(msg.find("new java.util.ArrayList<>()") != std::string::npos);
}

TEST_CASE("Java: protocol class has type registry", "[codegen][java]") {
    auto java = gen_java("choice_protocol.bmdl.xml");
    REQUIRE(java.has_value());
    auto& prot = java->files["Protocol.java"];
    CHECK(prot.find("public final class Protocol") != std::string::npos);
    CHECK(prot.find("TypeInfo") != std::string::npos);
    CHECK(prot.find("findById") != std::string::npos);
    CHECK(prot.find("findByName") != std::string::npos);
}

TEST_CASE("Java: byte[] field toString uses Arrays.toString", "[codegen][java]") {
    auto java = gen_java("bytes_numeric.bmdl.xml");
    REQUIRE(java.has_value());
    REQUIRE(java->files.count("LargeBytesMsg.java"));
    auto& msg = java->files["LargeBytesMsg.java"];
    CHECK(msg.find("java.util.Arrays.toString(blob)") != std::string::npos);
}

TEST_CASE("Java: LE fields use false for big_endian", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("readU16(false)") != std::string::npos);
    CHECK(msg.find("readU32(false)") != std::string::npos);
}

TEST_CASE("Java: package declaration present", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    auto& msg = java->files["AllTypesMessage.java"];
    CHECK(msg.find("package all_types;") != std::string::npos);
}

TEST_CASE("Java: generates output for all_types fixture", "[codegen][java]") {
    auto java = gen_java("all_types.bmdl.xml");
    REQUIRE(java.has_value());
    CHECK(java->files.size() >= 8);
}

TEST_CASE("Java: generates output for major fixtures", "[codegen][java]") {
    std::vector<std::string> fixtures = {
        "choice_protocol.bmdl.xml", "arrays_choices.bmdl.xml",
        "string_features.bmdl.xml", "inline_field_types.bmdl.xml",
        "wire_encodings.bmdl.xml", "mixed_endian.bmdl.xml",
        "bitmap_fx.bmdl.xml", "constraints.bmdl.xml",
        "field_scale.bmdl.xml", "expr_features.bmdl.xml",
        "format_binary.bmdl.xml",
    };
    for (const auto& fixture : fixtures) {
        INFO("Fixture: " << fixture);
        auto java = gen_java(fixture);
        CHECK(java.has_value());
    }
}

// ============================================================================
// Float16 / variable-size float codegen tests
// ============================================================================

TEST_CASE("Java: float16 types generate readF16/writeF16", "[java][float]") {
    auto java = gen_java("float16_types.bmdl.xml");
    REQUIRE(java.has_value());

    // BitReader.java should have readF16
    REQUIRE(java->files.count("BitReader.java"));
    CHECK(java->files.at("BitReader.java").find("readF16") != std::string::npos);

    // BitWriter.java should have writeF16
    REQUIRE(java->files.count("BitWriter.java"));
    CHECK(java->files.at("BitWriter.java").find("writeF16") != std::string::npos);

    // The generated message class should use readF16/writeF16
    bool found_f16_read = false;
    bool found_f16_write = false;
    for (const auto& [name, content] : java->files) {
        if (content.find("readF16") != std::string::npos) found_f16_read = true;
        if (content.find("writeF16") != std::string::npos) found_f16_write = true;
    }
    CHECK(found_f16_read);
    CHECK(found_f16_write);
}

// ============================================================================
// Empty struct / message codegen tests
// ============================================================================

TEST_CASE("Java: empty struct with <empty/> generates valid code", "[java][empty]") {
    auto java = gen_java("empty_struct_explicit.bmdl.xml");
    REQUIRE(java.has_value());

    // There should be an EmptyExplicit.java and EmptyMsg.java
    bool found_empty_struct = false;
    bool found_empty_msg = false;
    for (const auto& [name, content] : java->files) {
        if (name == "EmptyExplicit.java") found_empty_struct = true;
        if (name == "EmptyMsg.java") found_empty_msg = true;
    }
    CHECK(found_empty_struct);
    CHECK(found_empty_msg);
}

// ============================================================================
// Java reserved-word field names
//
// Field names that are valid C++ identifiers but Java reserved words must be
// renamed by the Java backend (suffixed with '_'); otherwise the generated
// .java file fails to compile.
// ============================================================================

TEST_CASE("Java: Java-only reserved words in field names are suffixed with _",
          "[java][keywords]") {
    auto java = gen_java("java_only_keywords.bmdl.xml");
    REQUIRE(java.has_value());

    auto& msg = java->files.at("JavaKeywordMsg.java");

    // Each Java reserved word must appear as a renamed identifier.  We check
    // for the suffix form ("interface_") rather than the bare keyword to
    // avoid matching the language token itself (e.g., a `final` modifier on
    // some other declaration).
    for (const std::string kw :
         {"interface_", "implements_", "instanceof_", "extends_",
          "super_", "synchronized_", "transient_", "strictfp_",
          "finally_", "assert_", "throws_"}) {
        CAPTURE(kw);
        CHECK(msg.find(kw) != std::string::npos);
    }

    // And the bare keyword must NOT appear as an identifier with a leading
    // type ("int interface;" would be a hard compile error).
    CHECK(msg.find("int interface;") == std::string::npos);
    CHECK(msg.find("int implements;") == std::string::npos);
    CHECK(msg.find("int super;") == std::string::npos);
}
