// SPDX-License-Identifier: MIT
// Bgen tests - End-to-end codegen output validation

#include <catch2/catch_test_macros.hpp>
#include "../src/model/ast_builder.hpp"
#include "../src/analyzer/type_resolver.hpp"
#include "../src/analyzer/validator.hpp"
#include "../src/analyzer/wire_sizer.hpp"
#include "../src/analyzer/session_analyzer.hpp"
#include "../src/codegen/cpp_constants.hpp"
#include "../src/codegen/cpp_types.hpp"
#include "../src/codegen/cpp_structs.hpp"
#include "../src/codegen/cpp_session.hpp"
#include "../src/codegen/cpp_protocol.hpp"
#include "../src/codegen/cpp_umbrella.hpp"
#include "../src/codegen/name_utils.hpp"
#include <filesystem>
#include <string>
#include <iostream>

namespace fs = std::filesystem;

static std::string fixture_path(const std::string& name) {
    return (fs::path(BGEN_TEST_FIXTURES_DIR) / name).string();
}

// Helper: run the full codegen pipeline and return all generated code
struct GeneratedCode {
    std::string constants;
    std::string types;
    std::string structs;
    std::string messages;
    std::string sessions;
    std::string protocol;
    std::string umbrella;
};

static std::optional<GeneratedCode> generate_from(const std::string& fixture_name) {
    auto build_result = bgen::model::build_protocol(fixture_path(fixture_name));
    if (!build_result) return std::nullopt;
    auto& protocol = *build_result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    if (!resolve_result) return std::nullopt;
    auto& index = *resolve_result;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);

    std::string ns = protocol.name;
    for (char& c : ns) {
        if (c == '-') c = '_';
    }

    GeneratedCode gc;
    gc.constants = bgen::codegen::generate_constants(protocol, index, ns);
    gc.types = bgen::codegen::generate_types(protocol, ns);
    gc.structs = bgen::codegen::generate_structs(protocol, index, sizes, sessions, ns);
    gc.messages = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);
    gc.sessions = bgen::codegen::generate_sessions(protocol, index, sessions, ns);
    gc.protocol = bgen::codegen::generate_protocol(protocol, sessions, ns);
    gc.umbrella = bgen::codegen::generate_umbrella(bgen::codegen::to_lower_snake_case(protocol.name));
    return gc;
}

TEST_CASE("Generate code from minimal protocol", "[codegen]") {
    auto gc = generate_from("minimal.bmdl.xml");
    REQUIRE(gc.has_value());

    // All outputs should be non-empty
    CHECK_FALSE(gc->constants.empty());
    CHECK_FALSE(gc->types.empty());
    CHECK_FALSE(gc->structs.empty());
    CHECK_FALSE(gc->messages.empty());
    CHECK_FALSE(gc->sessions.empty());
    CHECK_FALSE(gc->protocol.empty());
    CHECK_FALSE(gc->umbrella.empty());

    // All should start with generated header
    CHECK(gc->constants.find("Generated by bgen") != std::string::npos);
    CHECK(gc->types.find("Generated by bgen") != std::string::npos);
    CHECK(gc->structs.find("Generated by bgen") != std::string::npos);
    CHECK(gc->messages.find("Generated by bgen") != std::string::npos);
    CHECK(gc->sessions.find("Generated by bgen") != std::string::npos);
    CHECK(gc->protocol.find("Generated by bgen") != std::string::npos);
    CHECK(gc->umbrella.find("Generated by bgen") != std::string::npos);

    // Messages should contain SimpleMessage class
    CHECK(gc->messages.find("class SimpleMessage") != std::string::npos);
    CHECK(gc->messages.find("TYPE_ID") != std::string::npos);
    CHECK(gc->messages.find("TYPE_NAME") != std::string::npos);
}

TEST_CASE("Generate code from choice protocol", "[codegen]") {
    auto gc = generate_from("choice_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // Session should contain FrameSession class
    CHECK(gc->sessions.find("FrameSession") != std::string::npos);
    CHECK(gc->sessions.find("decode_frame") != std::string::npos);
    CHECK(gc->sessions.find("encode_wrap") != std::string::npos);

    // decode_frame should use std::visit for payload dispatch
    CHECK(gc->sessions.find("std::visit") != std::string::npos);

    // encode_wrap should reference leaf types
    CHECK(gc->sessions.find("AlphaBody") != std::string::npos);

    // Protocol descriptor should exist
    CHECK(gc->protocol.find("ProtocolDescriptor") != std::string::npos);
    CHECK(gc->protocol.find("create_session") != std::string::npos);
    CHECK(gc->protocol.find("\"choice_test\"") != std::string::npos);

    // Umbrella should include protocol.hpp
    CHECK(gc->umbrella.find("protocol.hpp") != std::string::npos);
}

TEST_CASE("Generated session has proper discriminator checks", "[codegen]") {
    auto gc = generate_from("choice_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // v2 frame-based sessions use std::visit on payload variant, not
    // the old dm.payload = *frame pattern.  Verify the old pattern is absent.

    // Count occurrences of "dm.payload = *frame"
    size_t pos = 0;
    int frame_stuff_count = 0;
    while ((pos = gc->sessions.find("dm.payload = *frame", pos)) != std::string::npos) {
        frame_stuff_count++;
        pos += 10;
    }
    CHECK(frame_stuff_count == 0);
}

TEST_CASE("Generated protocol descriptor has type registry", "[codegen]") {
    auto gc = generate_from("choice_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // Should have TypeInfo struct
    CHECK(gc->protocol.find("struct TypeInfo") != std::string::npos);
    CHECK(gc->protocol.find("type_id") != std::string::npos);
    CHECK(gc->protocol.find("type_name") != std::string::npos);

    // Should have find functions
    CHECK(gc->protocol.find("find(uint64_t type_id)") != std::string::npos);
    CHECK(gc->protocol.find("find(std::string_view type_name)") != std::string::npos);

    // Should list leaf types
    CHECK(gc->protocol.find("AlphaBody") != std::string::npos);
    CHECK(gc->protocol.find("BetaBody") != std::string::npos);
}

// ============================================================================
// Advanced codegen output validation
// ============================================================================

TEST_CASE("Inline struct codegen", "[codegen]") {
    auto gc = generate_from("inline_struct.bmdl.xml");
    REQUIRE(gc.has_value());

    // Session should contain FrameSession
    CHECK(gc->sessions.find("FrameSession") != std::string::npos);

    // Inline struct should result in sync, seq fields directly in session
    CHECK(gc->sessions.find("sync") != std::string::npos);
    CHECK(gc->sessions.find("encode_wrap") != std::string::npos);
}

TEST_CASE("Session auto-sequence in generated code", "[codegen]") {
    auto gc = generate_from("session_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // Session should contain sequence counter member
    CHECK(gc->sessions.find("sequence_counter_") != std::string::npos);
}

TEST_CASE("Session sync constraint in generated code", "[codegen]") {
    auto gc = generate_from("session_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // wrap() in messages should set the sync constant
    CHECK(gc->messages.find("SYNC") != std::string::npos);
}

TEST_CASE("Direction filtering in codegen", "[codegen]") {
    auto gc = generate_from("choice_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // In generated sessions, decode_frame appears before encode_wrap
    auto decode_frame_pos = gc->sessions.find("decode_frame");
    auto encode_wrap_pos = gc->sessions.find("encode_wrap");
    REQUIRE(decode_frame_pos != std::string::npos);
    REQUIRE(encode_wrap_pos != std::string::npos);

    // Extract the encode_wrap function body (from encode_wrap signature to the
    // next function — approximate by taking a reasonable slice)
    // Find the closing brace of encode_wrap by looking for the next top-level function
    auto after_encode = gc->sessions.find("sync_pattern", encode_wrap_pos);
    REQUIRE(after_encode != std::string::npos);
    std::string encode_section = gc->sessions.substr(encode_wrap_pos,
        after_encode - encode_wrap_pos);

    // v2 decode_frame uses std::visit (generic lambda) — type names appear in encode_wrap
    // AlphaBody (no direction restriction) should appear in encode_wrap section
    CHECK(encode_section.find("AlphaBody") != std::string::npos);

    // BetaBody (direction="receive") should appear in encode_wrap section
    // (direction is documentary — encode succeeds with a runtime warning)
    CHECK(encode_section.find("BetaBody") != std::string::npos);
}

TEST_CASE("FX block codegen succeeds", "[codegen]") {
    auto gc = generate_from("fx_block.bmdl.xml");
    REQUIRE(gc.has_value());

    // Should generate non-empty messages
    CHECK_FALSE(gc->messages.empty());
    CHECK(gc->messages.find("FxMessage") != std::string::npos);
}

TEST_CASE("Default value codegen", "[codegen]") {
    auto gc = generate_from("default_initial.bmdl.xml");
    REQUIRE(gc.has_value());

    // Generated structs or messages should reference default values
    CHECK(gc->messages.find("DefaultMsg") != std::string::npos);
    CHECK(gc->messages.find("InitialMsg") != std::string::npos);
    // Default values should appear in member declarations
    CHECK(gc->messages.find("{1}") != std::string::npos);  // version default
    CHECK(gc->messages.find("{100}") != std::string::npos); // counter default
    // ConstraintDefaultMsg: constraint equals="42" implies default="42"
    CHECK(gc->messages.find("magic_{42}") != std::string::npos);
    // ConstraintDefaultMsg: inline field (bytes+bits) with explicit default
    CHECK(gc->messages.find("tag_{37}") != std::string::npos);
}

TEST_CASE("Expression codegen", "[codegen]") {
    auto gc = generate_from("expr_features.bmdl.xml");
    REQUIRE(gc.has_value());

    // Arithmetic in length-from should generate subtraction
    CHECK(gc->messages.find("ArithmeticLengthMsg") != std::string::npos);
}

TEST_CASE("Sentry-link session contains sequence counter", "[codegen]") {
    std::string sentry_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "sentry_link.bmdl.xml").string();
    if (!fs::exists(sentry_path)) {
        SKIP("sentry-link protocol not found");
    }

    auto build_result = bgen::model::build_protocol(sentry_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;
    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;
    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);
    std::string ns = "sentry_link";
    auto sessions_code = bgen::codegen::generate_sessions(protocol, index, sessions, ns);

    CHECK(sessions_code.find("sequence_counter_") != std::string::npos);
}

TEST_CASE("Sentry-link constraints in wrap", "[codegen]") {
    std::string sentry_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "sentry_link.bmdl.xml").string();
    if (!fs::exists(sentry_path)) {
        SKIP("sentry-link protocol not found");
    }

    auto build_result = bgen::model::build_protocol(sentry_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;
    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;
    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);
    std::string ns = "sentry_link";
    auto messages_code = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);

    // Wrap should set sync to SYNC constant (wrap is in messages, not sessions)
    CHECK(messages_code.find("SYNC") != std::string::npos);
}

TEST_CASE("Sentry-link direction filtering", "[codegen]") {
    std::string sentry_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "sentry_link.bmdl.xml").string();
    if (!fs::exists(sentry_path)) {
        SKIP("sentry-link protocol not found");
    }

    auto build_result = bgen::model::build_protocol(sentry_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;
    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;
    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);
    std::string ns = "sentry_link";
    auto sessions_code = bgen::codegen::generate_sessions(protocol, index, sessions, ns);

    // ConfigBody is direction="send", so should be in encode_wrap
    CHECK(sessions_code.find("ConfigBody") != std::string::npos);

    // HeartbeatBody, SensorBody, AlertBody are direction="receive", should be in decode_frame
    CHECK(sessions_code.find("HeartbeatBody") != std::string::npos);
    CHECK(sessions_code.find("SensorBody") != std::string::npos);
    CHECK(sessions_code.find("AlertBody") != std::string::npos);
}

TEST_CASE("Sentry-link end-to-end codegen", "[codegen]") {
    std::string sentry_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "sentry_link.bmdl.xml").string();
    if (!fs::exists(sentry_path)) {
        SKIP("sentry-link protocol not found");
    }

    auto build_result = bgen::model::build_protocol(sentry_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);

    std::string ns = "sentry_link";

    auto constants = bgen::codegen::generate_constants(protocol, index, ns);
    auto types = bgen::codegen::generate_types(protocol, ns);
    auto structs = bgen::codegen::generate_structs(protocol, index, sizes, sessions, ns);
    auto messages = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);
    auto sessions_code = bgen::codegen::generate_sessions(protocol, index, sessions, ns);
    auto protocol_code = bgen::codegen::generate_protocol(protocol, sessions, ns);
    auto umbrella = bgen::codegen::generate_umbrella(protocol.name);

    // All should be non-empty
    CHECK_FALSE(constants.empty());
    CHECK_FALSE(types.empty());
    CHECK_FALSE(structs.empty());
    CHECK_FALSE(messages.empty());
    CHECK_FALSE(sessions_code.empty());
    CHECK_FALSE(protocol_code.empty());
    CHECK_FALSE(umbrella.empty());

    // Session should mention all 4 leaf types
    CHECK(sessions_code.find("HeartbeatBody") != std::string::npos);
    CHECK(sessions_code.find("SensorBody") != std::string::npos);
    CHECK(sessions_code.find("ConfigBody") != std::string::npos);
    CHECK(sessions_code.find("AlertBody") != std::string::npos);

    // Protocol descriptor should have all types
    CHECK(protocol_code.find("ProtocolDescriptor") != std::string::npos);
    CHECK(protocol_code.find("sentry_link") != std::string::npos);
}

// ============================================================================
// ASTERIX protocol codegen tests
// ============================================================================

TEST_CASE("ASTERIX end-to-end codegen", "[codegen]") {
    std::string asterix_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "asterix.bmdl.xml").string();
    if (!fs::exists(asterix_path)) {
        SKIP("asterix protocol not found");
    }

    auto build_result = bgen::model::build_protocol(asterix_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);

    std::string ns = "asterix";

    auto constants = bgen::codegen::generate_constants(protocol, index, ns);
    auto types = bgen::codegen::generate_types(protocol, ns);
    auto structs = bgen::codegen::generate_structs(protocol, index, sizes, sessions, ns);
    auto messages = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);
    auto sessions_code = bgen::codegen::generate_sessions(protocol, index, sessions, ns);
    auto protocol_code = bgen::codegen::generate_protocol(protocol, sessions, ns);
    auto umbrella = bgen::codegen::generate_umbrella(protocol.name);

    // All outputs should be non-empty
    CHECK_FALSE(constants.empty());
    CHECK_FALSE(types.empty());
    CHECK_FALSE(structs.empty());
    CHECK_FALSE(messages.empty());
    CHECK_FALSE(sessions_code.empty());
    CHECK_FALSE(protocol_code.empty());
    CHECK_FALSE(umbrella.empty());

    // All should have generated header
    CHECK(constants.find("Generated by bgen") != std::string::npos);
    CHECK(structs.find("Generated by bgen") != std::string::npos);
    CHECK(messages.find("Generated by bgen") != std::string::npos);
}

TEST_CASE("ASTERIX bitmap-controlled choice codegen", "[codegen]") {
    std::string asterix_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "asterix.bmdl.xml").string();
    if (!fs::exists(asterix_path)) {
        SKIP("asterix protocol not found");
    }

    auto build_result = bgen::model::build_protocol(asterix_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);
    std::string ns = "asterix";

    auto messages = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);

    // Cat253Record's bitmap struct should contain the i100 choice variant
    // The bitmap is a child of the message, so it appears in messages output
    // Always-prefixed: parent bitmap struct "items" + "_" + "i100Variant"
    CHECK(messages.find("items_i100Variant") != std::string::npos);

    // The choice should use std::visit for encoding (not Variant::encode)
    CHECK(messages.find("std::visit") != std::string::npos);

    // The choice decode should use switch expression with -> for optional bitmap field
    // i080 is an optional bitmap field, so i080.structure-selector should generate i080_->
    CHECK(messages.find("i080_->") != std::string::npos);

    // All five format types should appear in the variant
    CHECK(messages.find("Cat253I100FormatA") != std::string::npos);
    CHECK(messages.find("Cat253I100FormatB") != std::string::npos);
    CHECK(messages.find("Cat253I100FormatC") != std::string::npos);
    CHECK(messages.find("Cat253I100FormatD") != std::string::npos);
    CHECK(messages.find("Cat253I100FormatE") != std::string::npos);

    // Should NOT contain Variant::decode (the old broken pattern)
    CHECK(messages.find("items_i100Variant::decode") == std::string::npos);
}

TEST_CASE("ASTERIX FSPEC bitmap structs", "[codegen]") {
    std::string asterix_path = (fs::path(BGEN_TEST_FIXTURES_DIR) / "asterix.bmdl.xml").string();
    if (!fs::exists(asterix_path)) {
        SKIP("asterix protocol not found");
    }

    auto build_result = bgen::model::build_protocol(asterix_path);
    REQUIRE(build_result.has_value());
    auto& protocol = *build_result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;

    auto sizes = bgen::analyzer::compute_wire_sizes(protocol, index);
    auto sessions = bgen::analyzer::analyze_sessions(protocol, index);
    std::string ns = "asterix";

    auto messages = bgen::codegen::generate_messages(protocol, index, sizes, sessions, ns);

    // Bitmap structs inside messages should use FSPEC encoding
    CHECK(messages.find("fspec") != std::string::npos);

    // Cat001Record, Cat048Record, Cat253Record bitmap structs should have optional fields
    CHECK(messages.find("std::optional") != std::string::npos);
    CHECK(messages.find("DataBlock") != std::string::npos);
    CHECK(messages.find("Cat001Record") != std::string::npos);
    CHECK(messages.find("Cat048Record") != std::string::npos);
    CHECK(messages.find("Cat253Record") != std::string::npos);
}

// ============================================================================
// Deep-inspection fixes
// ============================================================================

TEST_CASE("FX block with string/bytes generates correct encode", "[codegen]") {
    auto gc = generate_from("fx_string.bmdl.xml");
    REQUIRE(gc.has_value());

    // String in FX should use value_or(""), NOT value_or(0)
    CHECK(gc->messages.find("value_or(\"\")") != std::string::npos);
    // Should NOT contain value_or(0) applied to strings
    // (value_or(0) should only appear for the uint16 extra field)

    // Bytes in FX should use has_value() + write_bytes, not value_or(0)
    CHECK(gc->messages.find("write_bytes") != std::string::npos);

    // Struct zero-fill should use encode() not write_bits
    // (This validates the sub-byte precision fix)
    CHECK(gc->messages.find("write_string") != std::string::npos);
}

TEST_CASE("String length-includes-prefix generates underflow guard", "[codegen]") {
    auto gc = generate_from("string_prefix_incl.bmdl.xml");
    REQUIRE(gc.has_value());

    // The generated message decode should contain a bounds check before
    // subtracting prefix bytes from the received length value
    CHECK(gc->messages.find("length-prefix value smaller than prefix size") != std::string::npos);
    CHECK(gc->messages.find("BufferOverrun") != std::string::npos);
}

// ============================================================================
// Wire encoding codegen output validation
// ============================================================================

TEST_CASE("Wire encoding codegen generates BCD/BNR_S calls", "[codegen][wire_encoding]") {
    auto gc = generate_from("wire_encodings.bmdl.xml");
    REQUIRE(gc.has_value());

    // Messages should contain WireEncodingMsg class
    CHECK(gc->messages.find("class WireEncodingMsg") != std::string::npos);

    // Should use read_bcd for BCD-encoded fields
    CHECK(gc->messages.find("read_bcd(") != std::string::npos);

    // Should use read_bcd_signed for BCD_S-encoded fields
    CHECK(gc->messages.find("read_bcd_signed(") != std::string::npos);

    // Should use read_sign_magnitude for BNR_S-encoded fields
    CHECK(gc->messages.find("read_sign_magnitude(") != std::string::npos);

    // Should use write_bcd for BCD-encoded fields
    CHECK(gc->messages.find("write_bcd(") != std::string::npos);

    // Should use write_bcd_signed for BCD_S-encoded fields
    CHECK(gc->messages.find("write_bcd_signed(") != std::string::npos);

    // Should use write_sign_magnitude for BNR_S-encoded fields
    CHECK(gc->messages.find("write_sign_magnitude(") != std::string::npos);
}

TEST_CASE("Wire encoding codegen CB2/BNR use standard read/write", "[codegen][wire_encoding]") {
    auto gc = generate_from("wire_encodings.bmdl.xml");
    REQUIRE(gc.has_value());

    // CB2 (two's complement) and BNR (unsigned) are the defaults,
    // so they should generate standard read_signed_bits / read_bits calls.
    // The generated code should NOT use read_bcd or read_sign_magnitude for cb2/bnr fields.
    // We can verify by checking that standard read methods are present.
    CHECK(gc->messages.find("read_signed_bits(") != std::string::npos);
    CHECK(gc->messages.find("read_bits(") != std::string::npos);
}

// ============================================================================
// Advanced feature codegen tests (bitmap, enum arrays, FX advanced)
// ============================================================================

TEST_CASE("Bitmap with enum, string, bytes, BCD codegen succeeds", "[codegen][bitmap]") {
    auto gc = generate_from("bitmap_advanced.bmdl.xml");
    REQUIRE(gc.has_value());

    // All outputs should be non-empty
    CHECK_FALSE(gc->structs.empty());
    CHECK_FALSE(gc->messages.empty());

    // Should contain the AdvancedBitmap struct with optional fields
    CHECK(gc->structs.find("AdvancedBitmap") != std::string::npos);
    CHECK(gc->structs.find("std::optional") != std::string::npos);

    // Should contain the BitmapAdvancedMsg message
    CHECK(gc->messages.find("BitmapAdvancedMsg") != std::string::npos);

    // Enum field in bitmap should reference status-code type (snake_case in C++)
    CHECK(gc->types.find("status_code") != std::string::npos);

    // BCD field in bitmap should use read_bcd
    CHECK(gc->structs.find("read_bcd(") != std::string::npos);
    CHECK(gc->structs.find("write_bcd(") != std::string::npos);

    // String field in bitmap should use read_string/write_string
    CHECK(gc->structs.find("read_string(") != std::string::npos);
    CHECK(gc->structs.find("write_string(") != std::string::npos);

    // Bytes field in bitmap should use read_bytes/write_bytes
    CHECK(gc->structs.find("read_bytes(") != std::string::npos);
    CHECK(gc->structs.find("write_bytes(") != std::string::npos);
}

TEST_CASE("Enum arrays codegen succeeds", "[codegen][array]") {
    auto gc = generate_from("enum_arrays.bmdl.xml");
    REQUIRE(gc.has_value());

    // All outputs should be non-empty
    CHECK_FALSE(gc->messages.empty());
    CHECK_FALSE(gc->types.empty());

    // Should contain the EnumArrayMsg message
    CHECK(gc->messages.find("EnumArrayMsg") != std::string::npos);

    // Should contain the command-code enum type (snake_case in C++)
    CHECK(gc->types.find("command_code") != std::string::npos);

    // All arrays use std::vector in codegen (both fixed and variable size)
    CHECK(gc->messages.find("std::vector") != std::string::npos);

    // Enum array decode should use decode_command_code function (not .decode() method)
    CHECK(gc->messages.find("decode_command_code(") != std::string::npos);

    // Enum array encode should use encode_command_code function (not .encode() method)
    CHECK(gc->messages.find("encode_command_code(") != std::string::npos);

    // BCD array should use read_bcd for decode
    CHECK(gc->messages.find("read_bcd(") != std::string::npos);
}

TEST_CASE("FX block to_string uses std::to_string for numeric optionals (B3)", "[codegen]") {
    auto gc = generate_from("fx_block.bmdl.xml");
    REQUIRE(gc.has_value());

    // B3 fix: to_string() for optional numeric fields should show the actual
    // value via std::to_string, not just "set"/"none".
    // FxMessage has optional uint16 item1, uint32 item2, uint8 item3
    // All are simple numeric types -> should use std::to_string(*member)
    CHECK(gc->messages.find("std::to_string(") != std::string::npos);

    // Should NOT have bare "set" for numeric optional fields in to_string output
    // (But "set" may still appear for non-numeric optional fields like structs)
}

TEST_CASE("FX choice codegen succeeds (B1/B2)", "[codegen][fx]") {
    auto gc = generate_from("fx_choice.bmdl.xml");
    REQUIRE(gc.has_value());

    // FxChoiceMsg should be generated
    CHECK(gc->messages.find("FxChoiceMsg") != std::string::npos);

    // Choice inside FX should generate variant type
    CHECK(gc->messages.find("CaseABody") != std::string::npos);
    CHECK(gc->messages.find("CaseBBody") != std::string::npos);

    // B1: has_fields_check should work on optional variant (choice in FX)
    // B2: encode should handle is_optional=true for choice in FX
    // If either bug existed, codegen would fail or produce uncompilable code
    CHECK(gc->messages.find("std::visit") != std::string::npos);
}

TEST_CASE("FX advanced features codegen succeeds", "[codegen][fx]") {
    auto gc = generate_from("fx_advanced.bmdl.xml");
    REQUIRE(gc.has_value());

    // All outputs should be non-empty
    CHECK_FALSE(gc->structs.empty());
    CHECK_FALSE(gc->messages.empty());

    // Should contain the FxAdvancedMsg message
    CHECK(gc->messages.find("FxAdvancedMsg") != std::string::npos);

    // Should contain the FxSubStruct struct (nested struct in FX)
    CHECK(gc->structs.find("FxSubStruct") != std::string::npos);

    // Scaled field in FX should have scale/offset conversion
    CHECK(gc->messages.find("scaled_temp") != std::string::npos);

    // Enum field in FX should reference fx-status type (snake_case in C++)
    CHECK(gc->types.find("fx_status") != std::string::npos);

    // String in FX should use read_string/write_string
    CHECK(gc->messages.find("read_string(") != std::string::npos);
    CHECK(gc->messages.find("write_string(") != std::string::npos);

    // Nested FX block should work (struct and array fields inside)
    // The struct field should use FxSubStruct::decode
    CHECK(gc->messages.find("FxSubStruct::decode(") != std::string::npos);

    // Array in nested FX should be generated
    CHECK(gc->messages.find("values") != std::string::npos);
}

// ============================================================================
// generate_umbrella() output validation
// ============================================================================

TEST_CASE("generate_umbrella includes all expected headers", "[codegen][umbrella]") {
    auto gc = generate_from("minimal.bmdl.xml");
    REQUIRE(gc.has_value());

    // Umbrella header should include all six generated headers
    CHECK(gc->umbrella.find("#include \"constants.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"types.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"structs.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"messages.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"sessions.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"protocol.hpp\"") != std::string::npos);

    // Should have pragma once
    CHECK(gc->umbrella.find("#pragma once") != std::string::npos);

    // Should reference the protocol name
    CHECK(gc->umbrella.find("minimal") != std::string::npos);

    // Should have the generated-by header
    CHECK(gc->umbrella.find("Generated by bgen") != std::string::npos);
}

TEST_CASE("generate_umbrella for hyphenated protocol name", "[codegen][umbrella]") {
    auto gc = generate_from("sentry_link.bmdl.xml");
    REQUIRE(gc.has_value());

    // Protocol name derived from namespace (sentry_link)
    CHECK(gc->umbrella.find("sentry_link") != std::string::npos);

    // All six includes should still be present
    CHECK(gc->umbrella.find("#include \"constants.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"types.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"structs.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"messages.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"sessions.hpp\"") != std::string::npos);
    CHECK(gc->umbrella.find("#include \"protocol.hpp\"") != std::string::npos);
}

TEST_CASE("generate_umbrella uses snake_case name", "[codegen][umbrella]") {
    auto gc = generate_from("inline_field_types.bmdl.xml");
    REQUIRE(gc.has_value());

    // Umbrella should reference the snake_cased protocol name
    CHECK(gc->umbrella.find("inline_field_types") != std::string::npos);
    CHECK(gc->umbrella.find("#pragma once") != std::string::npos);
}

TEST_CASE("generate_umbrella does not contain hyphens for hyphenated names", "[codegen][umbrella]") {
    // sentry_link fixture — protocol name is "sentry-link" which should become "sentry_link"
    auto gc = generate_from("sentry_link.bmdl.xml");
    REQUIRE(gc.has_value());

    // Should not contain a hyphenated name in the umbrella
    // The comment line should use the snake_cased name
    CHECK(gc->umbrella.find("sentry_link") != std::string::npos);
}

// ============================================================================
// generate_protocol() output validation
// ============================================================================

TEST_CASE("generate_protocol contains ProtocolDescriptor with expected members", "[codegen][protocol]") {
    auto gc = generate_from("choice_protocol.bmdl.xml");
    REQUIRE(gc.has_value());

    // ProtocolDescriptor struct
    CHECK(gc->protocol.find("struct ProtocolDescriptor") != std::string::npos);

    // Protocol metadata: name and version
    CHECK(gc->protocol.find("static constexpr std::string_view name") != std::string::npos);
    CHECK(gc->protocol.find("static constexpr std::string_view version") != std::string::npos);
    CHECK(gc->protocol.find("\"choice_test\"") != std::string::npos);

    // TypeInfo struct with expected fields
    CHECK(gc->protocol.find("struct TypeInfo") != std::string::npos);
    CHECK(gc->protocol.find("uint64_t type_id") != std::string::npos);
    CHECK(gc->protocol.find("std::string_view type_name") != std::string::npos);
    CHECK(gc->protocol.find("std::span<const std::string_view> groups") != std::string::npos);

    // Types array
    CHECK(gc->protocol.find("static constexpr std::array<TypeInfo,") != std::string::npos);

    // Lookup functions
    CHECK(gc->protocol.find("find(uint64_t type_id)") != std::string::npos);
    CHECK(gc->protocol.find("find(std::string_view type_name)") != std::string::npos);

    // Session factory
    CHECK(gc->protocol.find("create_session()") != std::string::npos);

    // Namespace
    CHECK(gc->protocol.find("namespace choice_test") != std::string::npos);

    // Standard includes
    CHECK(gc->protocol.find("#include \"sessions.hpp\"") != std::string::npos);
    CHECK(gc->protocol.find("#include <array>") != std::string::npos);
    CHECK(gc->protocol.find("#include <cstdint>") != std::string::npos);
    CHECK(gc->protocol.find("#include <memory>") != std::string::npos);
    CHECK(gc->protocol.find("#include <span>") != std::string::npos);
    CHECK(gc->protocol.find("#include <string_view>") != std::string::npos);
    CHECK(gc->protocol.find("#include <conduit/traits/session_traits.hpp>") != std::string::npos);
}

TEST_CASE("generate_protocol for protocol without sessions", "[codegen][protocol]") {
    auto gc = generate_from("minimal.bmdl.xml");
    REQUIRE(gc.has_value());

    // ProtocolDescriptor should still be generated
    CHECK(gc->protocol.find("struct ProtocolDescriptor") != std::string::npos);
    CHECK(gc->protocol.find("\"minimal\"") != std::string::npos);

    // TypeInfo struct should still exist
    CHECK(gc->protocol.find("struct TypeInfo") != std::string::npos);

    // Types array should be empty (no sessions means no leaf types)
    CHECK(gc->protocol.find("std::array<TypeInfo, 0>") != std::string::npos);

    // No create_session factory when there are no sessions
    CHECK(gc->protocol.find("create_session") == std::string::npos);
}

// ============================================================================
// Newly registered fixture codegen validation
// ============================================================================

TEST_CASE("send_only_leaf codegen succeeds", "[codegen]") {
    auto gc = generate_from("send_only_leaf.bmdl.xml");
    REQUIRE(gc.has_value());

    // All outputs should be non-empty
    CHECK_FALSE(gc->constants.empty());
    CHECK_FALSE(gc->types.empty());
    CHECK_FALSE(gc->structs.empty());
    CHECK_FALSE(gc->messages.empty());
    CHECK_FALSE(gc->sessions.empty());
    CHECK_FALSE(gc->protocol.empty());

    // Entry-point Frame should generate a session
    CHECK(gc->sessions.find("FrameSession") != std::string::npos);

    // Both leaf types should appear in protocol descriptor
    CHECK(gc->protocol.find("SendBody") != std::string::npos);
    CHECK(gc->protocol.find("RecvBody") != std::string::npos);

    // SendBody (direction="send") should appear in encode_wrap
    CHECK(gc->sessions.find("SendBody") != std::string::npos);

    // RecvBody (direction="receive") should appear in decode_frame
    CHECK(gc->sessions.find("RecvBody") != std::string::npos);
}

TEST_CASE("non_overlap_ranges codegen succeeds", "[codegen]") {
    auto gc = generate_from("non_overlap_ranges.bmdl.xml");
    REQUIRE(gc.has_value());

    // Should generate non-empty output
    CHECK_FALSE(gc->messages.empty());
    CHECK_FALSE(gc->structs.empty());

    // Msg message with range-based choice should be generated
    CHECK(gc->messages.find("Msg") != std::string::npos);

    // BodyA and BodyB struct types should be present
    CHECK(gc->structs.find("BodyA") != std::string::npos);
    CHECK(gc->structs.find("BodyB") != std::string::npos);
}

// ============================================================================
// Frame-based codegen output tests (v2)
// ============================================================================

TEST_CASE("frame_basic: frame class in generated messages", "[codegen][frame]") {
    auto gc = generate_from("frame_basic.bmdl.xml");
    REQUIRE(gc.has_value());

    // Frame class should be in messages.hpp
    CHECK(gc->messages.find("class SimpleFrame") != std::string::npos);

    // Payload variant
    CHECK(gc->messages.find("PayloadVariant") != std::string::npos);
    CHECK(gc->messages.find("std::variant<Heartbeat, Status>") != std::string::npos);

    // ID_VALUE on messages
    CHECK(gc->messages.find("ID_VALUE = 1") != std::string::npos);
    CHECK(gc->messages.find("ID_VALUE = 2") != std::string::npos);

    // Frame wrap() overloads
    CHECK(gc->messages.find("wrap(const Heartbeat&") != std::string::npos);
    CHECK(gc->messages.find("wrap(const Status&") != std::string::npos);

    // Frame encode with length backpatch
    CHECK(gc->messages.find("length_byte_pos_") != std::string::npos);
    CHECK(gc->messages.find("patch_u16") != std::string::npos);

    // Frame decode with id-based switch
    CHECK(gc->messages.find("switch") != std::string::npos);
    CHECK(gc->messages.find("case 1:") != std::string::npos);
    CHECK(gc->messages.find("case 2:") != std::string::npos);

    // Messages should NOT have v1 wrap() overloads
    // (v1 wrap is on entry-point, v2 wrap is on frame class)
    // Heartbeat class should not contain wrap(const Status&)
    auto heartbeat_pos = gc->messages.find("class Heartbeat");
    auto frame_pos = gc->messages.find("class SimpleFrame");
    REQUIRE(heartbeat_pos != std::string::npos);
    REQUIRE(frame_pos != std::string::npos);
    // The wrap overloads should only appear in the frame class (after message classes)
    auto wrap_heartbeat = gc->messages.find("wrap(const Heartbeat&");
    CHECK(wrap_heartbeat > frame_pos);
}

TEST_CASE("frame_basic: session generated for frame", "[codegen][frame]") {
    auto gc = generate_from("frame_basic.bmdl.xml");
    REQUIRE(gc.has_value());

    // Session class
    CHECK(gc->sessions.find("SimpleFrameSession") != std::string::npos);
    CHECK(gc->sessions.find("ISession") != std::string::npos);

    // Factory function
    CHECK(gc->sessions.find("create_simple_frame_session") != std::string::npos);

    // decode_frame using Frame::decode_bytes
    CHECK(gc->sessions.find("SimpleFrame::decode_bytes") != std::string::npos);

    // encode_wrap using Frame::wrap
    CHECK(gc->sessions.find("SimpleFrame::wrap") != std::string::npos);
}

TEST_CASE("frame_config: config struct in session", "[codegen][frame]") {
    auto gc = generate_from("frame_config.bmdl.xml");
    REQUIRE(gc.has_value());

    // Config struct in session class
    CHECK(gc->sessions.find("struct Config") != std::string::npos);
    CHECK(gc->sessions.find("system_id") != std::string::npos);

    // Config parameter in constructor
    CHECK(gc->sessions.find("const Config& config") != std::string::npos);

    // Config parameter in factory
    CHECK(gc->sessions.find("create_config_frame_session") != std::string::npos);

    // Config field set during encode_wrap
    CHECK(gc->sessions.find("config_.system_id") != std::string::npos);
}

TEST_CASE("frame_basic: protocol descriptor for frame", "[codegen][frame]") {
    auto gc = generate_from("frame_basic.bmdl.xml");
    REQUIRE(gc.has_value());

    CHECK(gc->protocol.find("ProtocolDescriptor") != std::string::npos);
    CHECK(gc->protocol.find("create_session") != std::string::npos);
    CHECK(gc->protocol.find("create_simple_frame_session") != std::string::npos);
}

TEST_CASE("frame_footer: frame class has footer field", "[codegen][frame]") {
    auto gc = generate_from("frame_footer.bmdl.xml");
    REQUIRE(gc.has_value());

    // Frame class should exist
    CHECK(gc->messages.find("class FooterFrame") != std::string::npos);

    // Checksum accessor
    CHECK(gc->messages.find("checksum") != std::string::npos);

    // Footer field read after payload decode
    CHECK(gc->messages.find("checksum_val_") != std::string::npos);

    // Length backpatch with error check (not silently swallowed)
    CHECK(gc->messages.find("patch_u") != std::string::npos);
    CHECK(gc->messages.find("failed to patch frame length") != std::string::npos);
}

TEST_CASE("frame_direction: direction-qualified messages", "[codegen][frame]") {
    auto gc = generate_from("frame_direction.bmdl.xml");
    REQUIRE(gc.has_value());

    // All three message types present
    CHECK(gc->messages.find("class CommandRequest") != std::string::npos);
    CHECK(gc->messages.find("class CommandResponse") != std::string::npos);
    CHECK(gc->messages.find("class Heartbeat") != std::string::npos);

    // Both share ID=1 but different directions
    // The frame decode switch dispatches both on case 1 (recv direction preferred)
    CHECK(gc->messages.find("case 1:") != std::string::npos);
    CHECK(gc->messages.find("case 2:") != std::string::npos);

    // Session should have direction warning code
    CHECK(gc->sessions.find("send-only") != std::string::npos);
}

TEST_CASE("frame_array: array payload codegen", "[codegen][frame]") {
    auto gc = generate_from("frame_array.bmdl.xml");
    REQUIRE(gc.has_value());

    // Array payload type
    CHECK(gc->messages.find("class ArrayFrame") != std::string::npos);
    CHECK(gc->messages.find("std::vector") != std::string::npos);

    // Decode loop for array payload
    CHECK(gc->messages.find("while") != std::string::npos);
}

TEST_CASE("fx_ia5_string: FX string with IA5 encoding codegen", "[codegen][fx]") {
    auto gc = generate_from("fx_ia5_string.bmdl.xml");
    REQUIRE(gc.has_value());

    // FX string encode should use from_ascii for IA5 conversion
    // FxIa5Msg is a <message>, so its encode code is in messages output
    CHECK(gc->messages.find("from_ascii") != std::string::npos);
}

TEST_CASE("mutable_X() emplaces empty optional", "[codegen]") {
    // Optional fields should generate mutable_X() that emplaces if empty
    auto gc = generate_from("struct_features.bmdl.xml");
    REQUIRE(gc.has_value());

    // Generated mutable_ accessor should contain .emplace() to avoid bad_optional_access
    auto code = gc->structs + gc->messages;
    if (code.find("mutable_") != std::string::npos) {
        CHECK(code.find(".emplace()") != std::string::npos);
    }
}

TEST_CASE("frame_length_offset: offset appears in session codegen", "[codegen][frame]") {
    auto gc = generate_from("frame_length_offset.bmdl.xml");
    REQUIRE(gc.has_value());

    // extract_frame_length should reverse the Sub(3) modifier by adding 3
    CHECK(gc->sessions.find("+ 3)") != std::string::npos);
}

TEST_CASE("SourceLoc shows line:column in error messages", "[parser]") {
    // Parse a known-invalid file and check error location format
    auto result = bgen::model::build_protocol(fixture_path("invalid_keyword_name.bmdl.xml"));
    REQUIRE(result.has_value());
    auto& protocol = *result;

    auto resolve_result = bgen::analyzer::resolve_types(protocol);
    REQUIRE(resolve_result.has_value());
    auto& index = *resolve_result;

    auto validate_result = bgen::analyzer::validate(protocol, index);
    REQUIRE_FALSE(validate_result.has_value());

    // Error location should contain line:column format, not "offset(N)"
    auto& errors = validate_result.error();
    REQUIRE_FALSE(errors.empty());
    bool has_line_col = false;
    for (const auto& e : errors) {
        // Location should be embedded in the error message as "file:LINE:COL: ..."
        // The error struct has a loc field
        auto loc_str = e.loc.to_string();
        if (loc_str.find("offset(") == std::string::npos && loc_str.find(":") != std::string::npos) {
            has_line_col = true;
            break;
        }
    }
    CHECK(has_line_col);
}

// ============================================================================
// Section: Bool type generation
// ============================================================================

TEST_CASE("Bool field generates bool getter and setter", "[codegen][bool]") {
    auto gc = generate_from("inline_field_types.bmdl.xml");
    REQUIRE(gc.has_value());

    // Getter should return bool, not uint8_t
    CHECK(gc->messages.find("bool active()") != std::string::npos);
    CHECK(gc->messages.find("uint8_t active()") == std::string::npos);

    // Setter should take bool by value
    CHECK(gc->messages.find("set_active(bool") != std::string::npos);
}

// ============================================================================
// Section: Inline enum codegen
// ============================================================================

TEST_CASE("Inline enum generates enum class", "[codegen][inline_enum]") {
    auto gc = generate_from("inline_enum.bmdl.xml");
    REQUIRE(gc.has_value());

    // Should generate enum class for inline enum field
    CHECK(gc->messages.find("enum class InlineEnumMsg_Mode") != std::string::npos);
    CHECK(gc->messages.find("enum class InlineEnumMsg_Priority") != std::string::npos);

    // Should generate encode/decode functions
    CHECK(gc->messages.find("encode_InlineEnumMsg_Mode") != std::string::npos);
    CHECK(gc->messages.find("decode_InlineEnumMsg_Mode") != std::string::npos);

    // Field accessor should return the enum type
    CHECK(gc->messages.find("InlineEnumMsg_Mode mode()") != std::string::npos);
}

// ============================================================================
// Section: Always-prefix child class naming
// ============================================================================

TEST_CASE("Child classes always have parent prefix", "[codegen][child_prefix]") {
    auto gc = generate_from("asterix.bmdl.xml");
    REQUIRE(gc.has_value());

    // All child classes should have parent prefix — no bare "items", "sub", "spf"
    // at struct namespace scope
    CHECK(gc->messages.find("Cat001Record_items") != std::string::npos);
    // Verify no bare "class items" at namespace scope (would appear as "class items {")
    // The bare name should not appear without a parent prefix
}

TEST_CASE("Child class of arrays_choices has parent prefix", "[codegen][child_prefix]") {
    auto gc = generate_from("arrays_choices.bmdl.xml");
    REQUIRE(gc.has_value());

    // All generated code should compile and child classes should have prefixed names
    CHECK(!gc->structs.empty());
    CHECK(!gc->messages.empty());
}

// ============================================================================
// Section: Outer-scope field access + auto-length (outer_scope fixture)
// ============================================================================

TEST_CASE("Outer scope: generates parameterized decode for otherwise case", "[codegen][outer_scope]") {
    auto gc = generate_from("outer_scope.bmdl.xml");
    REQUIRE(gc.has_value());

    // The otherwise case's inline struct should have a decode signature
    // that accepts the outer-scope "len" field as a parameter
    CHECK(gc->structs.find("uint8 len") != std::string::npos);
}

TEST_CASE("Outer scope: auto-length backpatch in encode", "[codegen][outer_scope]") {
    auto gc = generate_from("outer_scope.bmdl.xml");
    REQUIRE(gc.has_value());

    // Encode should contain auto-length backpatch logic
    CHECK(gc->structs.find("struct_start_pos_") != std::string::npos);
    CHECK(gc->structs.find("length_byte_pos_") != std::string::npos);
    CHECK(gc->structs.find("patch_u8") != std::string::npos);
}

// ============================================================================
// Section: Fix verification tests (C3, inline enum value semantics)
// ============================================================================

TEST_CASE("to_string overload always generated", "[codegen][C3]") {
    // C3 fix: the span-accepting to_string overload must be generated for every
    // struct/message regardless of whether it has auto-managed frame fields.
    // This allows format_outbound to call to_string(overrides) on any message.
    auto gc = generate_from("minimal.bmdl.xml");
    REQUIRE(gc.has_value());

    // The messages output should contain the span-accepting overload signature
    auto& code = gc->messages;
    CHECK(code.find("to_string(std::span<const std::pair<std::string, std::string>>") != std::string::npos);
}

TEST_CASE("enum accessor returns by value not reference", "[codegen][inline_enum]") {
    // Inline enum accessors should return by value (not const ref) since enums
    // are small scalar types.
    auto gc = generate_from("inline_enum.bmdl.xml");
    REQUIRE(gc.has_value());

    auto& code = gc->messages;

    // Getter should return InlineEnumMsg_Mode by value
    CHECK(code.find("InlineEnumMsg_Mode mode()") != std::string::npos);
    // Getter should NOT return by const reference
    CHECK(code.find("const InlineEnumMsg_Mode& mode()") == std::string::npos);
    CHECK(code.find("const InlineEnumMsg_Mode &mode()") == std::string::npos);

    // Setter should take InlineEnumMsg_Mode by value
    CHECK(code.find("set_mode(InlineEnumMsg_Mode") != std::string::npos);
    // Setter should NOT take by const reference
    CHECK(code.find("set_mode(const InlineEnumMsg_Mode&") == std::string::npos);
}

// ============================================================================
// Payload length-from codegen
// ============================================================================

TEST_CASE("payload length-from generates sub_reader in decode", "[codegen][payload_length_from]") {
    auto gc = generate_from("frame_payload_length_from.bmdl.xml");
    REQUIRE(gc.has_value());

    // The messages file should contain the Frame class with decode
    auto& code = gc->messages;
    CHECK(code.find("class ExprFrame") != std::string::npos);

    // decode() should create a bounded sub_reader from body-size expression
    CHECK(code.find("sub_reader") != std::string::npos);
    CHECK(code.find("body_size") != std::string::npos);
}

// ============================================================================
// format="binary" codegen
// ============================================================================

TEST_CASE("format binary generates bitset in to_string", "[codegen][format_binary]") {
    auto gc = generate_from("format_binary.bmdl.xml");
    REQUIRE(gc.has_value());

    // The generated code should use std::bitset for binary-formatted fields
    auto& code = gc->messages;
    CHECK(code.find("std::bitset<64>") != std::string::npos);
    // Should include the 0b prefix in the to_string output
    CHECK(code.find("0b") != std::string::npos);
}

TEST_CASE("generated structs header includes bitset", "[codegen][format_binary]") {
    auto gc = generate_from("format_binary.bmdl.xml");
    REQUIRE(gc.has_value());

    // The structs header should include <bitset>
    CHECK(gc->structs.find("#include <bitset>") != std::string::npos);
    // The messages header should include <bitset>
    CHECK(gc->messages.find("#include <bitset>") != std::string::npos);
}
