[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "conduit-example-xcvr-python"
version = "1.1.6"
description = "ASTERIX Transceiver Example — Python"
requires-python = ">=3.10"

dependencies = [
    "conduit>=1.1.6",
]

[project.scripts]
poc-app = "src.poc_app:main"
dummy-peer = "src.dummy_peer:main"
