plugins {
    id 'java'
    id 'application'
}

group = 'com.conduit'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            srcDirs = [
                'src/main/java',
                'asterix/generated',
                'asterix-alt/generated'
            ]
        }
    }
}

application {
    mainClass = 'com.conduit.xcvr.PocApp'
}

tasks.register('runPocApp', JavaExec) {
    mainClass = 'com.conduit.xcvr.PocApp'
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runDummyPeer', JavaExec) {
    mainClass = 'com.conduit.xcvr.DummyPeer'
    classpath = sourceSets.main.runtimeClasspath
}
