// SPDX-License-Identifier: MIT
// Bgen - Umbrella Header Generator Implementation

#include "cpp_umbrella.hpp"
#include "emit_context.hpp"

namespace bgen::codegen {

std::string generate_umbrella(const std::string& protocol_name) {
    EmitContext ctx;

    ctx.line("// Generated by bgen - DO NOT EDIT");
    ctx.line("// Umbrella header for: " + protocol_name);
    ctx.line("#pragma once");
    ctx.line();
    ctx.line("#include \"constants.hpp\"");
    ctx.line("#include \"types.hpp\"");
    ctx.line("#include \"structs.hpp\"");
    ctx.line("#include \"messages.hpp\"");
    ctx.line("#include \"sessions.hpp\"");
    ctx.line("#include \"protocol.hpp\"");
    ctx.line();

    return ctx.str();
}

} // namespace bgen::codegen
