// SPDX-License-Identifier: MIT
// Bgen - Constants Code Generator Implementation

#include "cpp_constants.hpp"
#include "emit_context.hpp"
#include "name_utils.hpp"
#include <charconv>

namespace bgen::codegen {

std::string generate_constants(const model::Protocol& protocol,
                               const analyzer::TypeIndex& index,
                               const std::string& ns) {
    EmitContext ctx;

    ctx.line("// Generated by bgen - DO NOT EDIT");
    ctx.line("#pragma once");
    ctx.line();
    ctx.line("#include <cstdint>");
    ctx.line();
    ctx.line("namespace " + ns + " {");
    ctx.line();

    for (const auto& c : protocol.constants) {
        if (!c.doc.empty()) {
            ctx.comment(c.doc);
        }

        // Determine C++ type
        std::string cpp_type = "uint32_t";
        auto it = index.types.find(c.type_ref);
        if (it != index.types.end()) {
            const auto& td = *it->second;
            if (td.base == model::PrimitiveBase::Uint || td.base == model::PrimitiveBase::Int) {
                bool is_signed = (td.base == model::PrimitiveBase::Int);
                cpp_type = storage_type_for_bits(td.bits, is_signed);
            }
        }

        // Format value
        std::string value_str = c.value;
        // If hex, keep hex format
        if (value_str.size() > 2 && value_str[0] == '0' && (value_str[1] == 'x' || value_str[1] == 'X')) {
            // Already hex, good
        }

        ctx.line("inline constexpr " + cpp_type + " " + c.name + " = " + value_str + ";");
    }

    ctx.line();
    ctx.line("} // namespace " + ns);
    ctx.line();

    return ctx.str();
}

} // namespace bgen::codegen
