// SPDX-License-Identifier: MIT
// Bgen - Protocol Descriptor Generator Implementation

#include "cpp_protocol.hpp"
#include "emit_context.hpp"
#include "name_utils.hpp"
#include <set>

namespace bgen::codegen {

std::string generate_protocol(const model::Protocol& protocol,
                              const std::vector<analyzer::SessionInfo>& sessions,
                              const std::string& ns) {
    EmitContext ctx;

    ctx.line("// Generated by bgen - DO NOT EDIT");
    ctx.line("#pragma once");
    ctx.line();
    ctx.line("#include \"sessions.hpp\"");
    ctx.line("#include <conduit/traits/session_traits.hpp>");
    ctx.line("#include <array>");
    ctx.line("#include <cstdint>");
    ctx.line("#include <memory>");
    ctx.line("#include <span>");
    ctx.line("#include <string_view>");
    ctx.line();
    ctx.line("namespace " + ns + " {");
    ctx.line();

    ctx.line("struct ProtocolDescriptor {");
    ctx.indent();

    // Protocol metadata
    std::string safe_name = protocol.name;
    for (char& c : safe_name) {
        if (c == '-') c = '_';
    }
    ctx.line("static constexpr std::string_view name = \"" + protocol.name + "\";");
    ctx.line("static constexpr std::string_view version = \"" + protocol.version + "\";");
    ctx.line();

    // Collect all unique leaf types across all sessions
    struct TypeEntry {
        uint64_t type_id;
        std::string type_name;
        std::vector<std::string> groups; // from annotations with key "group"
    };
    std::vector<TypeEntry> all_types;
    // Track seen type_ids to avoid duplicates
    std::vector<uint64_t> seen_ids;

    for (const auto& si : sessions) {
        for (const auto& lt : si.leaf_types) {
            bool found = false;
            for (auto id : seen_ids) {
                if (id == lt.type_id) { found = true; break; }
            }
            if (!found) {
                seen_ids.push_back(lt.type_id);
                TypeEntry entry;
                entry.type_id = lt.type_id;
                entry.type_name = lt.name;
                // Extract groups from annotations with key "group"
                for (const auto& [key, value] : lt.annotations) {
                    if (key == "group") {
                        // Support comma-separated groups
                        std::string remaining = value;
                        size_t pos = 0;
                        while (pos < remaining.size()) {
                            size_t comma = remaining.find(',', pos);
                            std::string group;
                            if (comma == std::string::npos) {
                                group = remaining.substr(pos);
                                pos = remaining.size();
                            } else {
                                group = remaining.substr(pos, comma - pos);
                                pos = comma + 1;
                            }
                            // Trim whitespace
                            while (!group.empty() && group.front() == ' ') group.erase(group.begin());
                            while (!group.empty() && group.back() == ' ') group.pop_back();
                            if (!group.empty()) entry.groups.push_back(group);
                        }
                    }
                }
                all_types.push_back(std::move(entry));
            }
        }
    }

    // Collect all unique group names (use set for O(n log n) vs O(n²))
    std::set<std::string> group_set;
    for (const auto& t : all_types) {
        for (const auto& g : t.groups) {
            group_set.insert(g);
        }
    }
    std::vector<std::string> all_groups(group_set.begin(), group_set.end());

    // Group string constants (for constexpr span references)
    if (!all_groups.empty()) {
        for (size_t i = 0; i < all_groups.size(); i++) {
            ctx.line("static constexpr std::string_view group_" + std::to_string(i) +
                     " = \"" + all_groups[i] + "\";");
        }
        ctx.line();

        // Per-type group arrays
        for (size_t ti = 0; ti < all_types.size(); ti++) {
            const auto& t = all_types[ti];
            if (!t.groups.empty()) {
                ctx.line("static constexpr std::string_view type_" + std::to_string(ti) +
                         "_groups[] = {");
                ctx.indent();
                for (size_t gi = 0; gi < t.groups.size(); gi++) {
                    // Find group index
                    for (size_t k = 0; k < all_groups.size(); k++) {
                        if (all_groups[k] == t.groups[gi]) {
                            std::string comma = (gi + 1 < t.groups.size()) ? "," : "";
                            ctx.line("group_" + std::to_string(k) + comma);
                            break;
                        }
                    }
                }
                ctx.dedent();
                ctx.line("};");
            }
        }
        ctx.line();
    }

    // TypeInfo struct
    ctx.line("struct TypeInfo {");
    ctx.indent();
    ctx.line("uint64_t type_id;");
    ctx.line("std::string_view type_name;");
    ctx.line("std::span<const std::string_view> groups;");
    ctx.dedent();
    ctx.line("};");
    ctx.line();

    // Types array
    ctx.line("static constexpr std::array<TypeInfo, " + std::to_string(all_types.size()) + "> types = {{");
    ctx.indent();
    for (size_t i = 0; i < all_types.size(); i++) {
        const auto& t = all_types[i];
        std::string comma = (i + 1 < all_types.size()) ? "," : "";
        std::string groups_ref;
        if (t.groups.empty()) {
            groups_ref = "{}";
        } else {
            groups_ref = "type_" + std::to_string(i) + "_groups";
        }
        ctx.line("{" + type_id_literal(t.type_id) + ", \"" + t.type_name + "\", " + groups_ref + "}" + comma);
    }
    ctx.dedent();
    ctx.line("}};");
    ctx.line();

    // Lookup by type_id
    ctx.line("static constexpr const TypeInfo* find(uint64_t type_id) {");
    ctx.indent();
    ctx.line("for (const auto& t : types) {");
    ctx.indent();
    ctx.line("if (t.type_id == type_id) return &t;");
    ctx.dedent();
    ctx.line("}");
    ctx.line("return nullptr;");
    ctx.dedent();
    ctx.line("}");
    ctx.line();

    // Lookup by type_name
    ctx.line("static constexpr const TypeInfo* find(std::string_view type_name) {");
    ctx.indent();
    ctx.line("for (const auto& t : types) {");
    ctx.indent();
    ctx.line("if (t.type_name == type_name) return &t;");
    ctx.dedent();
    ctx.line("}");
    ctx.line("return nullptr;");
    ctx.dedent();
    ctx.line("}");
    ctx.line();

    // Session factory — one per entry-point
    if (!sessions.empty()) {
        const auto& first_session = sessions[0];
        if (first_session.is_frame_based && first_session.frame) {
            std::string factory_func = "create_" + to_lower_snake_case(first_session.frame->name) + "_session";
            std::string session_class = to_cpp_type_name(first_session.frame->name) + "Session";
            // Check if session has any config fields (frame-level or message-level)
            bool has_any_config = !first_session.config_fields.empty();
            if (!has_any_config) {
                for (const auto& lt : first_session.leaf_types) {
                    if (!lt.config_fields.empty()) { has_any_config = true; break; }
                }
            }
            if (has_any_config) {
                // Config-parameterized factory
                ctx.line("static std::unique_ptr<conduit::traits::ISession> create_session(const "
                         + session_class + "::Config& config) {");
                ctx.indent();
                ctx.line("return " + factory_func + "(config);");
                ctx.dedent();
                ctx.line("}");
            } else {
                ctx.line("static std::unique_ptr<conduit::traits::ISession> create_session() {");
                ctx.indent();
                ctx.line("return " + factory_func + "();");
                ctx.dedent();
                ctx.line("}");
            }
        }
    }

    ctx.dedent();
    ctx.line("};");
    ctx.line();

    ctx.line("} // namespace " + ns);
    ctx.line();

    return ctx.str();
}

} // namespace bgen::codegen
